Repository softberg/quantum-php-core, pull requests merged in 2022-10, with the labels that each got.

#89 New helper function to check route by group name
  src/Helpers/mvc.php
  tests/unit/Helpers/HelperTest.php
Labels: new feature

#91 Memcached adapter with unit test
  .travis.yml
  src/Exceptions/CacheException.php
  src/Libraries/Cache/Adapters/DatabaseAdapter.php
  src/Libraries/Cache/Adapters/FileAdapter.php
  src/Libraries/Cache/Adapters/MemecachedAdapter.php
  tests/unit/Libraries/Cache/Adapters/DatabaseAdaptereTest.php
  tests/unit/Libraries/Cache/Adapters/FileAdapterTest.php
  tests/unit/Libraries/Cache/Adapters/MemcachedAdapterTest.php
  tests/unit/Libraries/Cache/CacheTest.php
Labels: enhancement, new feature

#87 Swager integration for API module
  composer.json
  src/Console/Commands/DebugBarAssetsCommand.php
  src/Console/Commands/OpenApiUiAssetsCommand.php
  src/Helpers/misc.php
Labels: new feature

#93 Cache library (RedisCache adapter)
  .travis.yml
  src/Libraries/Cache/Adapters/RedisAdapter.php
  tests/unit/Libraries/Cache/Adapters/RedisAdapterTest.php
Labels: new feature

#94 Correcting issues on CacheManager
  src/Libraries/Cache/Adapters/MemcachedAdapter.php
  src/Libraries/Cache/CacheManager.php
  tests/unit/Libraries/Cache/Adapters/MemcachedAdapterTest.php
Labels: bug
